<?php
/*
Plugin Name: Ajax iTunes to WP v2
Plugin URI: http://leandermelms.me/
Description: Communicates with the iTunes API and lets users posting tracks from the front end without page refresh.
Author: Leander Melms
Version: 2.0.1
Author URI: http://leandermelms.me/
*/

 /***************************************************************************
 *
 *  ----------------------------------------------------------------------
 *        DO NOT EDIT THIS FILE UNLESS YOU'RE KNOWING WHAT YOU DO
 *                
 *  ----------------------------------------------------------------------
 * 
 *              Designed und build by Leander Melms
 *               Copyright (C) 2013 Leander Melms 
 *                   (http://leandermelms.me/)
 *
 ***************************************************************************/


// Instantiate Plugin Class
class iTunesLivePost {

    private $plugin_path;
    private $plugin_url;
    private $l10n;
    private $itlp;

    public function __construct() 
    {   
        // Globals
        define('LMURL', WP_PLUGIN_URL."/".dirname( plugin_basename( __FILE__ ) ) );
        define('LMPATH', WP_PLUGIN_DIR."/".dirname( plugin_basename( __FILE__ ) ) );

        // Vars
        $this->plugin_path = plugin_dir_path( __FILE__ );
        $this->plugin_url = plugin_dir_url( __FILE__ );
        $this->l10n = 'iTunesLivePort-framework';   // Textdomain

        $this->itlp_actions();
        $this->itlp_res();
        $this->itlp_setup();

        // Get settings
        $lm_data = itlp_get_settings( $this->plugin_path .'settings/settings-general.php' );
        $this->lm_generate_options_css($lm_data); //generate static css file
    }

    public function itlp_actions(){

        register_activation_hook( __FILE__, 'lm_handle_plugin_activation' );    
        register_deactivation_hook( __FILE__, 'lm_handle_plugin_deactivation' );
        add_action( 'admin_menu', array(&$this, 'admin_menu'), 99 ); // Admin Menu
        add_action('wp_enqueue_scripts', 'lm_enqueuescripts');
        add_action('widgets_init', 'lm_widget_init');
        add_action( 'wp_ajax_nopriv_lm_addpost', 'lm_addpost' );
        add_action( 'wp_ajax_lm_addpost', 'lm_addpost' );
        // Admin Scripts
        if ( is_admin() ) {
            add_action('admin_enqueue_scripts', 'lm_admin_scripts' );
        }
    }

    public function itlp_res(){
        require_once(ABSPATH . '/wp-config.php');
        require_once( $this->plugin_path .'/admin/iTunesLivePort-framework.php' );  // Settings Framework
        require_once($this->plugin_path . '/lib/lm-functions.php');                 // Main Fuctions
        require_once($this->plugin_path . '/lib/post-type.php');                    // Track Post Type
        require_once($this->plugin_path . '/lib/lm-widget.php');                    // Search Widget
        require_once($this->plugin_path . '/lib/lm-comment.php');                   // Takes care of the comments template
        require_once($this->plugin_path . '/lib/lm-shortcodes.php');                // Views
        require_once($this->plugin_path . '/lib/lm-rating.php');                    // Ajax Raing
        require_once($this->plugin_path . '/lib/lm-ajax-form.php');                 // Widget Form
        require_once($this->plugin_path . '/lib/lm-charts.php');                    // Charts
        require_once($this->plugin_path . '/lib/mce/lm_shortcodes_tinymce.php');    // Shortcodes Helper
        require_once($this->plugin_path . '/class/lm.star-class.php');              // Ajax Rating Class
    }

    public function itlp_setup(){

        $this->itlp = new ITLPFramework( $this->plugin_path .'/admin/settings/settings-general.php' );
        add_filter( $this->itlp->get_option_group() .'_settings_validate', array(&$this, 'validate_settings') );        
    }

    public function admin_menu() {
        $page_hook = add_menu_page( __( 'ITLP', $this->l10n ), __( 'ITLP', $this->l10n ), 'update_core', 'ITLP', array(&$this, 'settings_page') );
        add_submenu_page( 'ITLP', __( 'Affiliate', $this->l10n ), __( 'Affiliate', $this->l10n ), 'update_core', 'itlp-aff', array(&$this, 'sub_settings_page') );
        add_submenu_page( 'ITLP', __( 'Statistics', $this->l10n ), __( 'Statistics', $this->l10n ), 'update_core', 'itlp-statt', array(&$this, 'sub_settings_charts') );
    }
    
    public function settings_page() {
        ?>
        <div class="wrap iTunesLivePost-options">
            <div id="icon-options-general" class="icon32"></div>
            <h2>iTunes Live Post Settings</h2>
            <div class="options-wrapr">
            <?php 
                // Output your settings form
                $this->itlp->settings();
            ?>
            <a href="#" id="prev-btn-triggr" class="prev-btn admin-btn" style="display:none"> Preview </a>
            </div>
        </div>
        <?php
    }

    public function sub_settings_page() {
        ?>
        <div class="wrap iTunesLivePost-options">
            <div id="icon-options-general" class="icon32"></div>
            <h2>iTunes Affiliate Setup</h2>
            <p> The iTunes Affiliate program provides a mechanism to earn extra revenue from your links which is up to 5% of the original price. </p>
            <p> As the iTunes Affiliate program is quite advanced, it is highly recommended to first familiarize yourself with it. </p>
            <h4> Basic Information </h4>
             <ol>
                <li> To make use of Apple's affiliate system, you first need to register your site/company with LinkShare (US) / TradeDoubler (EU) / DGM.</li>
                <li> The plugin requires to keys to setup Affiliate Links: The Partner ID, and the Affiliate Token </li>
                <li> Both, the Partner ID and the Affiliate Token differ from which Link System you have chosen </li>
            </ol>

            <br>

            <div class="options-wrapr">
                <h3> Partner ID </h3>
                <table border="0" class="table widefat" style="display:none">
                    <tbody>
                        <tr>
                            <td>Affiliate Network</td>
                            <td>partnerId</td>
                        </tr>
                        <tr>
                            <td>LinkShare</td>
                            <td>30</td>
                        </tr>
                        <tr>
                            <td>TradeDoubler</td>
                            <td>2003</td>
                        </tr>
                        <tr>
                            <td>DGM</td>
                            <td>1002</td>
                     </tr>
                    </tbody>
                </table>
            <h3> Affiliate Token </h3>
                <table border="0" class="table widefat" style="display:none">
                    <tbody>
                        <tr>
                            <td>Affiliate Network</td>
                            <td>Description</td>
                        </tr>
                        <tr>
                            <td>LinkShare</td>
                            <td>
                                <p>To identify your AffiliateToken (or also known as "SiteID"):</p>
                                <ol>
                                    <li>Open your LinkShare page and head over to the “Links” tab.</li>
                                    <li>Locate the "US iTunes, App Store, iBookstore, and Mac App Store” section and select it.</li>
                                    <li>Click on the "Link Maker Tool" from the toolbar at the top of this page.</li>
                                    <li>Next, below the search box on this page you should see a paragraph starting "Your affiliate network is". Within the link part of this paragraph is an item of the form "…stat?id=CBIMl*gYY/8&offerid=…".Find this and extract the 11 digit id value from here. In this case this is <strong>CBIMl*gYY/8</strong>.</li>
                                </ol>
                            </td>
                        </tr>
                        <tr>
                            <td>TradeDoubler</td>
                            <td>Please refer to this <a href="http://www.apple.com/itunes/affiliates/resources/documentation/linking-to-the-itunes-music-store.html#apps"> document </a> and locate the section "TradeDoubler".</td>
                        </tr>
                        <tr>
                            <td>DGM</td>
                            <td>Please refer to this <a href="http://www.apple.com/itunes/affiliates/resources/documentation/linking-to-the-itunes-music-store.html#apps"> document </a> and locate the section "DGM".</td>
                     </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <?php
    }

    public function sub_settings_charts() {
        echo charts();
    }
    
    public function validate_settings( $input ){
        return $input;
    }


    public function lm_generate_options_css($newdata) {
        $css_dir = $this->plugin_path . '/css/'; 

        ob_start(); 
        require($css_dir . 'user-styles.php'); 

        $css = ob_get_clean();
        file_put_contents($css_dir . 'options.css', $css, LOCK_EX); // Save it
    }

}

new iTunesLivePost();

// Move Templates files upon activation to active theme
function lm_handle_plugin_activation(){
    require_once(ABSPATH . 'wp-admin/includes/file.php');
    WP_Filesystem();
    global $wp_filesystem;

    $dirsource  = dirname(__FILE__) . '/lib/templates/';

    
    if ($handle = opendir($dirsource)) {
        while (false !== ($file = readdir($handle))) {
            if (substr($file, 0, 12) == 'single-track' && $file != "." && $file != ".." || substr($file, 0, 6) == 'track-' && $file != "." && $file != "..") {
                $wp_filesystem->copy(
                    $dirsource . $file,
                    get_template_directory().'/' . $file,
                    true,
                    FS_CHMOD_FILE
                );
            }
        }
        closedir($handle);
    }
}

// Delete them
function lm_handle_plugin_deactivation(){
    require_once(ABSPATH . 'wp-admin/includes/file.php');
    WP_Filesystem();
    global $wp_filesystem;
    if ($handle = opendir(get_template_directory() . '/')) {
        while (false !== ($file = readdir($handle))) {
            if (substr($file, 0, 12) == 'single-track' && $file != "." && $file != ".." || substr($file, 0, 6) == 'track-' && $file != "." && $file != "..") {
                $wp_filesystem->delete(
                    get_template_directory() . '/' . $file
                );
            }
        }
    }
    closedir($handle);
}


// Assigning hooks to actions 
$LM =& new LM();
add_action('activate_lm-star-rating/init.php', array(&$LM, 'install')); /* only works on WP 2.x*/
add_action('init', array(&$LM, 'init'));
add_action('wp_head', array(&$LM, 'wp_head'));
